// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA4S9oDDX1lCqIxWyTYclCeff_NUhmmEKI',
    appId: '1:747323159225:web:f78460ab88cbfbc09c2168',
    messagingSenderId: '747323159225',
    projectId: 'whatspapp-messenger',
    authDomain: 'whatspapp-messenger.firebaseapp.com',
    storageBucket: 'whatspapp-messenger.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCtaSE1wrlTgJNRbyoKCnfX22JcboIiMHM',
    appId: '1:747323159225:android:28c45235babd05ad9c2168',
    messagingSenderId: '747323159225',
    projectId: 'whatspapp-messenger',
    storageBucket: 'whatspapp-messenger.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC5yZbLnqpDkJb5diGZpCWtHxQ_Xa7U6xw',
    appId: '1:747323159225:ios:5899ad18428cdd2d9c2168',
    messagingSenderId: '747323159225',
    projectId: 'whatspapp-messenger',
    storageBucket: 'whatspapp-messenger.appspot.com',
    iosClientId: '747323159225-bereege46rnav1c8iroo6bn0dvva4dfq.apps.googleusercontent.com',
    iosBundleId: 'com.example.whatsappClone',
  );
}
